### ISSUE TITLE
安卓设备无法找到 显示No Device

### ISSUE THREAD

**Issue by lhr000lhr** [Jiesean/ANCSReader#1]
iOS 设备 为iOS 10，已经用lightblue 开启 virtual peripherals，安卓5.0的系统，在系统的蓝牙里面已经配对了iOS设备，运行ReadANCS还是显示No Device

**Comment by brookwillow** [comment]
这个demo很久了，bug比较多，没有时间去修复。
我的操作步骤是这样的，蓝牙不配对，然后开启lOS lightblue虚拟Heart Rate  
peripheral , 这样连接过程中会要求配对，完成配对后，应该可以接收了。多试几次，应该可以。

**Comment by brookwillow** [comment]
修复了连接过程的bond问题

**Comment by delhmela** [comment]
It didn't work.I saw only NO DEVICE
